trigger:
- testingx-*

parameters:
- name: experimentalTemplate
  displayName: 'Use experimental build process?'
  type: boolean
  default: true

steps:
- ${{ if eq(parameters.experimentalTemplate, true) }}:
  - template: experimental.yml
- ${{ if not(eq(parameters.experimentalTemplate, true)) }}:
  - template: stable.yml
